power <- read.table("household_power_consumption.txt",header = TRUE,sep=';',skip = 66636, nrows = 2880)
colnames(power) <- c('Date','Time','Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3')
power$datetime <- paste(power$Date,power$Time)
power$datetime <- strptime(power$datetime,format="%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png",width = 480, height = 480, unit = "px")
par(mfrow = c(2, 2))
with(power,plot(datetime,Global_active_power,type='l',xlab = '', ylab = 'Global Active Power'))
with(power,plot(datetime,Voltage,type='l', ylab = 'Voltage'))
with(power,plot(datetime,Sub_metering_1,type='l',xlab = '', ylab = 'Energy sub metering'))
lines(power$datetime,power$Sub_metering_2,col='red')
lines(power$datetime,power$Sub_metering_3,col='blue')
legend("topright", lty = 1, col = c("black", "red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
with(power,plot(datetime,Global_reactive_power,type='l'))
dev.off()